import { o_url_api } from '../overrides/services/endpoints'

export const default_url_api = {

  login: '/auth/login',
  logout: '/auth/logout',
  loginCustomer: '/auth/customer/login-v2',
  //loginShop: '/auth/shop/login',
  loginShop: '/auth/shop/login-v2',
  loginBusiness: '/auth/business/login',

  uploadfile: '/storage/upload',
  uploadSignfile: '/storage/upload-sign',

  assetFindAll: '/asset/find-all',
  assetCreate: '/asset/create',
  assetFind: '/asset/find/',
  assetUpdate: '/asset/update/',
  assetColorFindAll: '/asset/get-colors',
  assetModelFindAll: '/asset/get-models',
  assetNameFindAll: '/asset/get-names',
  assetCapacityFindAll: '/asset/get-capacitys',
  assetSearch: '/asset/search',
  assetAddtoShop: '/asset/add-to-shop',
  assetSearchContains: '/asset/search-contains',

  assetImgCreate: '/asset-image/create',
  assetImgDetele: '/asset-image/delete/',

  assetTypeFindAll: '/asset-type/find-all',
  assetTypeFindAllActive: '/asset-type/find-all-active',
  assetTypeCreate: '/asset-type/create',
  assetTypeFind: '/asset-type/find/',
  assetTypeUpdate: '/asset-type/update/',

  nameFindAll: '/asset-name/find-all',
  nameCreate: '/asset-name/create',
  nameFind: '/asset-name/find/',
  nameUpdate: '/asset-name/update/',
  nameDelete: '/asset-name/delete/',

  colorFindAll: '/asset-color/find-all',
  colorCreate: '/asset-color/create',
  colorFind: '/asset-color/find/',
  colorUpdate: '/asset-color/update/',
  colorDelete: '/asset-color/delete/',

  capacityFindAll: '/asset-capacity/find-all',
  capacityCreate: '/asset-capacity/create',
  capacityFind: '/asset-capacity/find/',
  capacityUpdate: '/asset-capacity/update/',
  capacityDelete: '/asset-capacity/delete/',

  modelFindAll: '/asset-model/find-all',
  modelCreate: '/asset-model/create',
  modelFind: '/asset-model/find/',
  modelUpdate: '/asset-model/update/',
  modelDelete: '/asset-model/delete/',

  businessUnitFindAll: '/business-unit/find-all',
  businessUnitActiveFindAll: '/business-unit/find-all-active',
  businessUnitCreate: '/business-unit/create',
  businessUnitFind: '/business-unit/find/',
  businessUnitUpdate: '/business-unit/update/',
  businessUnitSearchContains: '/business-unit/search-contains',
  businessUnitGetRate: '/business-unit/get-rate-shop-group',

  customerCreditCreateAndUpdate: '/business-unit/customer-credit/update',
  customerCreditFindAll: '/business-unit/customer-credit/find-all',
  customerCreditFindOne: '/business-unit/customer-credit/history',

  customerFindAll: '/customer/find-all',
  customerCreate: '/customer/create',
  customerFind: '/customer/find/',
  customerUpdate: '/customer/update/',
  customerSearch: '/customer/search',
  customerMemoAdd: '/customer/memo/add',
  customerMemoFindAll: '/customer/memo/history',
  customerSearchContains: '/customer/search-contains',
  customerContractOfferExport: '/contract/export-excel-offers',

  contractFindAll: '/contract/find-all',

  contractApprovedFindAll: '/contract/find-all-approved',
  contractApprovedFindAllV2: '/contract/find-all-approvedv2',
  contractRefinanceFindAll: '/contract/find-all-refinance',
  contractSearch: '/contract/search',
  contractRefinanceFindAllExport: '/contract/export-refinance-excel',
  contractCompleteFindAll: '/contract/find-all-complete',
  contractWaitFindAll: '/contract/find-all-pending-complete',
  contractPostComplete: '/contract/complete',
  contractUpdateLockedContracts: '/contract/excel-update-locked',

  contractFindAllHistory: '/contract/find-all-history',
  contractCreate: '/contract/create',
  contractFind: '/contract/find/',
  contractFindData: '/contract/find-data/',
  contractUpdate: '/contract/update/',
  contractUpDoc: '/contract/update-doc/', // remove later
  contractUpDocV2: '/contract/update-document/',
  contractUpdateStatus: '/contract/update-status',
  contractUpdateCredit: '/contract/update-credit',
  contractGetRate: '/contract/get-rate',
  contractGetShop: '/contract/get-shop',
  contractGetLogHistory: '/contract/get-log-history',
  contractAddMessage: '/contract/add-message',
  contractAddImage: '/contract/add-image',
  contractAddSlip: '/contract/add-slip',
  contractRemoveImage: '/contract/remove-image',
  contractFilter: '/contract/filter-contract',
  customContract: '/contract/w/find/',

  contractTypeFindAll: '/contract-type/find-all',
  contractTypeCreate: '/contract-type/create',
  contractTypeFind: '/contract-type/find/',
  contractTypeUpdate: '/contract-type/update/',
  contractCancelFindAll: '/contract/find-all-cancel',

  employeeFindAll: '/employee/find-all',
  employeeCreate: '/employee/create',
  employeeFind: '/employee/find/',
  employeeUpdate: '/employee/update/',
  employeeUpdateActive: '/employee/update-active/',
  

  interestRateFindAll: '/interest-rate/find-all',
  interestRateCreate: '/interest-rate/create',
  interestRateFind: '/interest-rate/find/',
  interestRateUpdate: '/interest-rate/update/',

  provincesFindAll: '/province/find-all',
  provincesFindAllGuest: '/province/w/find-all',
  district: '/district/find-all/',
  subDistrict: '/subdistrict/find-all/',

  shopFindAll: '/shop/find-all',
  shopSearchContains: '/shop/search-contains',
  shopCreate: '/shop/create',
  shopExport: '/shop/export',
  shopFind: '/shop/find/',
  shopUpdate: '/shop/update/',
  shopSearch: '/shop/search',
  shopRelation: '/shop/shop-relation',

  shopReadyToAddBu: '/shop/shop-ready-to-add-bu',
  shopRegister: '/shop/w/create',
  shopAddBank: '/shop/add-bank',
  shopUpdateBank: '/shop/update-bank',
  shopDeleteBank: '/shop/del-bank',
  shopCommissionFindAll: '/shop/get-commission',

  shopGetBU: '/shop/get-bu',

  shopGroupFindAll: '/shop-group/find-all',
  shopGroupFindAllActive: '/shop-group/find-all-active',
  shopGroupCreate: '/shop-group/create',
  shopGroupFind: '/shop-group/find/',
  shopGroupUpdate: '/shop-group/update/',
  shopGroupShopGetFind: '/shop-group/get-shop',
  shopGroupBuConfigCreate: '/shop-group/create-config/',

  shopCustomerCreate: '/shop-customer/create',
  shopGroupFindAllGuest: '/shop-group/w/find-all',
  shopAddBu: '/shop/add-shop-bu',
  buGetShopGroup: '/business-unit/get-shop-group/',
  buGetShop: '/business-unit/get-shop/',
  buGetShopV2: '/business-unit/get-shop-v2/',
  buUpdateConfig: '/business-unit/update-config/',
  buUpdateLineConfig: '/business-unit/update-line-config/',
  businessUnitFindAllGuest: '/business-unit/w/find-all',
  buNofiyFindAll: '/business-unit/notify/find-all',
  buNotifyCreate: '/business-unit/notify/create',
  buNotifyUpdate: '/business-unit/notify/update/',

  insuranceTypesFindAll: '/insurance-type/find-all',
  insuranceTypesCreate: '/insurance-type/create',
  insuranceTypesFind: '/insurance-type/find/',
  insuranceTypesUpdate: '/insurance-type/update/',

  customerGetProfile: '/customer/w/get-profile',
  customerPaymentFindAllGuest: '/customer/w/get-contract',

  paymentFindAll: '/payment/find-all',
  inquiryPayment: '/payment/inquiry-payment',
  paymentResubmit: '/payment/resubmit',
  customerPaymentPreviewFind: '/payment/preview',
  customerPaymentPreviewClose: '/contract/w/close-contract-preview',

  verifyPayment: '/payment/bbl/verify',
  confirmPayment: '/payment/bbl/confirm',

  dashboardFindAll: '/admin/dashboard',
  dashboardFindAllV2: '/admin/dashboard-v2',
  leasingReportFindAll: '/admin/leasing-report',

  contractPDF: '/contract/generate/',
  contractCleanPDF: '/contract/generate-clean/',
  contractPDPA: '/contract/generate-pdpa/',
  contractCardID: '/contract/generate-cardid/',
  contractRC: '/contract/generate-receipt/',
  contractShopRC: '/contract/generate-shop-receipt/',
  contractShopRCSign: '/contract/shop-sign-rc-pdf/',

  contractGoodsReceiptPDF: '/contract/generate-goods-receipt/',
  contractRequestToPayPDF: '/contract/generate-request-topay/',
  contractRequestToPayDATA: '/contract/get-data-request-topay/',
  contractCloseToPDF: '/contract/generate-close-contract/',
  contractReturnReceiptToPDF: '/contract/generate-return-receipt/',

  createLinkSignature: '/contract/create-sign-link/',
  getSignPdf: '/contract/get-pdf-sign/',
  getSignPdfPdpa: '/contract/get-pdf-sign-pdpa/',
  getSignPdfCardID: '/contract/get-pdf-sign-cardid',
  getSignPdfReceipt: '/contract/get-pdf-sign-receipt',

  getSignInfo: '/contract/get-pdf-info/',
  SignPdf: '/contract/sign-pdf',

  bankFindAll: '/bank/find-all',
  ocr: '/storage/analyze',

  buCheckList: '/business-unit/check-list',
  buRelationUpdate: '/business-unit/update-relation',

  updateFcmToken: '/auth/update-fcm-token',
  buGetBankList: '/business-unit/get-bank',
  buDelBank: '/business-unit/del-bank',
  buAddBank: '/business-unit/add-bank',
  buUpdateBank: '/business-unit/update-bank',

  contractGetPayment: '/contract/get-payment',
  contractMakePayment: '/contract/make-payment',
  contractMakePaymentClose: '/contract/make-payment-close',
  contractAppvRestart: '/contract/contract-appv-restart',
  contractClosePreview: '/contract/close-contract-preview',
  contractPayload: '/contract/payload',
  getNotify: '/admin/get-notify',
  readNotify: '/admin/read-notify/',

  cancelQrcode: '/contract/cancel-qr-code',
  customerCancelQrcode: '/contract/w/cancel-qr-code',

  getPayment: '/payment/get-payment',
  customerGetPaymentClose: '/payment/w/get-payment-close',
  updatePayment: '/payment/update',
  cancelPaymentCash: '/payment/cancel',
  getPaymentClose: '/payment/get-payment-close',
  paymentCheckStatus: '/payment/check-status',
  dailyUpdateDashboard: '/admin/daily-update-dashboard',

  pvDashboardCEO: '/admin/pv/ceo-dashboard',
  dailyUpdateCredit: '/contract/daliy-update-credit',
  shopUpdateCredit: '/customer/shop-update-credit',
  invoiceFindAll: '/invoice/find-all',
  cancelContract: '/contract/cancel',
  updateLockDevice: '/contract/update-lock-device',
  getConfigTMS: '/admin/get-config-tms',
  updateConfigTMS: '/admin/update-config-tms',
  providerCreate: '/business-unit/provider_applock/create',
  providerPayload: '/business-unit/provider_applock/payload',
  providerUpdate: '/business-unit/provider_applock/update',
  providerList: '/business-unit/provider_applock',
  updateCreateCustomer: '/shop/update-create-customer',
  clearAllCache: '/admin/clear-all-cache',
  clearToken: '/admin/clear-token',
  reminderLine: '/customer/line/boardcast',

  // pv
  leasingReportPVFindAll: '/admin/pv/leasing-report',
  getCommissionPV: '/shop/pv/get-commission',
  getCommissionDetailPV: '/shop/pv/get-commission-detail',
  contractPVPayload: '/contract/pv/payload',
  contractPVCancel: '/contract/pv/cancel',
  contractPVUpdate: '/contract/pv/update',
  shopPaymentFindAll: '/payment/pv/find-all?tab=payment',
  shopPaymentDashboardFindAll: '/payment/pv/find-all?tab=dashboard',
  shopPaymentLogFindAll: '/payment/pv/find-all?tab=log',
  shopPaymentPayload: '/payment/pv/payload',
  shopPaymentPreview: '/payment/pv/preview',
  shopMakePayment: '/payment/pv/make-payment',
  addSlipPayment: '/payment/pv/add-slip',

  // line TODO: name=tpl ต้องดึงจาก bu
  lineDevLimet: '/messaging/quota',
  lineProdLimet: '/messaging/quota?name=tpl&mode=prod&date=20250311',

  announceFindAll: '/admin/announce/find-all',
  announceCreate: '/admin/announce/create',
  announceUpdate: '/admin/announce/update',
  announceDelete: '/admin/announce/delete',
  announcePayload: '/admin/announce/payload',
  announceShopGetData: '/admin/announce/shop-get-data',

  masterCustomerCredit: '/master/customer-credit',
  dashboardRepord: '/admin/dashboard-report',

  changeAssetShop: '/asset/change-asset-shop',

  paymentCallbackTest: '/payment/test-callback',

  refinanceUpdate: '/contract/refinance/update',
  contractSearchContains: '/contract/search-contains',

  bblValidate: '/payment/bbl/validate',
  bblConfirm: '/payment/bbl/confirm',
  bblFindALL: '/payment/bbl/find-all',
  bblFindOne: '/payment/bbl/find',
  bblInquiry: '/payment/bbl/inquiry',

  shopUserFindAll: '/shop-user/find-all',
  shopUserCreate: '/shop-user/create',
  shopUserFind: '/shop-user/find/',
  shopUserUpdate: '/shop-user/update/',

  ekycGetContract: '/webhook/panda/get-contract',
  ekycCreateContact: '/contract/create-ekyc',
  ekycUpdateContract: '/contract/update-ekyc-status',
  ekycCancelContract: '/contract/cancel-ekyc/',

  lineBoardCastOne:'/customer/line/boardcast-one',
  customerSearchProfile: '/customer/search-profile',
}

export const url_api = {
  ...default_url_api,
  ...o_url_api,
}